---
# Per environment values which override defaults in hmpps-breach-report-co-sso-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: breach-report-co-sso-api-dev.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.dev.json"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    NDELIUS-INTEGRATION-API_URL: "https://breach-report-co-sso-and-delius-dev.hmpps.service.justice.gov.uk"
    FRONTEND_URL: "https://breach-report-co-sso-ui-dev.hmpps.service.justice.gov.uk"

  allowlist:
    groups:
      - digital_staff_and_mojo
      - unilink_staff
      - moj_cloud_platform
      - delius-test

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-co-sso-notifications
